### ISSUE TITLE
Dual boot to disabled for offline updating driver pack

### ISSUE THREAD

**Issue by sreegitgub** [WOA-Project/Community-Issues#2]
### Description

do i need to disable dual boot before i proceed these steps?

How to offline update an existing Windows Desktop installation
Switch the device into mass storage.
Take note of the drive letter the Windows partition is using, here we will assume it got mounted as I:....

### Steps To Reproduce

  not applicable.

### Expected behavior

not applicable.

### Pictures/Screenshots

not applicable.

### What version of the UEFI are you currently running?

2.22

### UEFI Version (if not specified above)

2.12

### What version of the BSP are you currently running?

v2107.12

### Operating System

22000.132

### What device do you have?

Lumia 950 XL Dual SIM

### Stock Firmware

1078.00053

### Battery Vendor

MS

### Battery Manufacturing Date

11/2015

### Hardware Version

1.0.0.2

### Deployment type

I have deployed Windows using WOA Deployer and never updated using the Driver Updater utility

### Relevant Assets

yes

**Comment by sreegitgub** [comment]
its not required to disabled dual boot, hence closing this issue.

**Comment by gus33000** [comment]
Thank you for filing an issue on our community issue tracker. We noticed you cheated by entering false data into the form along the way. We wanted to take a moment to tell you that you really should enter correct values otherwise your feedback is going to get discarded.

Thanks again for your time, and glad it got resolved!
